### ISSUE TITLE
High level API (and/or wasm_bindgen CLI integration)

### ISSUE THREAD

**Issue by autodidaddict** [paritytech/wasmi#88] opened 2018-05-17 13:36 UTC
Ideally I'd like it to be as seamless to host a wasm module in Rust as it is to host it in JavaScript. wasm_bindgen creates wrappers that let us do things like easily invoke functions that accept strings, etc. Would it be possible to do something like this for Rust so that the interop is smoother? Apologies if something like this exists and I'm just not finding it

**Comment by pepyakin** [comment] 2018-05-17 13:47
Hi!

That's totally desirable! Indeed, when wasmi was designed we were trying to make it possible in future to provide seamless high-level API. However, priorities shifted since then. 

I didn't dig deep enough into wasm-bindgen, but I don't see anything that could prevent from creating similar wrappers.

**Comment by Robbepop** [comment] 2022-08-22 18:47
Nowadays we do have a `wasmi_cli` tool (not yet published on crates.io).
Therefore and also since this issue is quite dated I am going to close this issue for now.
We might just open another issue in the future for `wasm_bindgen` based API/integration (whatever that means).

**Closed by Robbepop** 2022-08-22 18:47 UTC
