### ISSUE TITLE
Main thread panics when trying to run examples

### ISSUE THREAD

**Issue by RazorSh4rk** [paritytech/wasmi#196] opened 2019-07-11 10:51 UTC
I was trying to run a wasm file with the interpreter in examples with 
`cargo rustc --release --example interpret -- examples/a.out.wasm `
but it failed with a panic. After that i tried [https://github.com/paritytech/wasmi/issues/127#issuecomment-451169817](url) thinking that i messed up something but i got the same error. Am i missing something? 

$RUST_BACKCTRACE=1, here is the trace
```
   Compiling wabt-sys v0.4.0
error: failed to run custom build command for `wabt-sys v0.4.0`

Caused by:
  process didn't exit successfully: `/home/razor/work/wasmi/target/release/build/wabt-sys-030b53c1a1a63a7e/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/razor/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.4.0/wabt" "-DBUILD_TESTS=OFF" "-DBUILD_TOOLS=OFF" "-DCMAKE_INSTALL_PREFIX=/home/razor/work/wasmi/target/release/build/wabt-sys-a092f0555cf39772/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- Using prebuilt re2c lexer
-- Configuring done
-- Generating done
-- Build files have been written to: /home/razor/work/wasmi/target/release/build/wabt-sys-a092f0555cf39772/out/build
running: "cmake" "--build" "." "--config" "Release" "--"
[  7%] Building CXX object CMakeFiles/libwabt.dir/src/utf8.cc.o
[  7%] Building CXX object CMakeFiles/libwabt.dir/src/lexer-source.cc.o
[  7%] Building CXX object CMakeFiles/libwabt.dir/src/tracing.cc.o
[ 10%] Building CXX object CMakeFiles/libwabt.dir/src/stream.cc.o

--- stderr
/home/razor/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.4.0/wabt/src/lexer-source.cc: In member function ‘virtual std::unique_ptr<wabt::LexerSource> wabt::LexerSourceFile::Clone()’:
/home/razor/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.4.0/wabt/src/lexer-source.cc:41:19: error: redundant move in return statement [-Werror=redundant-move]
   41 |   return std::move(result);
      |          ~~~~~~~~~^~~~~~~~
/home/razor/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.4.0/wabt/src/lexer-source.cc:41:19: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/libwabt.dir/build.make:167: CMakeFiles/libwabt.dir/src/lexer-source.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/libwabt.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /home/razor/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: cmake::fail
   8: cmake::run
   9: cmake::Config::build
  10: build_script_build::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by pepyakin** [comment] 2019-07-11 15:09
That's actually quite interesting. This is not an actually runtime panic but rather a panic in the build.rs of wabt-sys which is caused by a C++ compiler error.

I wonder what version of C++ you have installed?

**Comment by RazorSh4rk** [comment] 2019-07-12 08:39
```
gcc -v
gcc version 9.1.0 (GCC) 

cout<<__cplusplus;
201402
```

**Comment by pepyakin** [comment] 2019-07-12 11:24
Ok. It seems that you are building `wabt-sys v0.4.0` whereas the current version used by master is `v0.6.0`. Did you try to build the latest master?

**Comment by RazorSh4rk** [comment] 2019-07-12 13:06
I think i solved it? Pulled fresh, did a `cargo build && cargo test`, had the same issue, then added 
```
wabt-sys="0.6.0"
wabt="0.8.0"
```
to Cargo.toml and now its working.

**Comment by pepyakin** [comment] 2019-07-12 13:59
Closing then!

**Closed by pepyakin** 2019-07-12 13:59 UTC
